name = "isoopod/abserde"
version = "0.1.0"
description = "A Binary Storage Engine Reimagining Datastore Efficiency"
authors = ["isoopod"]
repository = "https://github.com/isoopod/abserde"
license = "MIT"
includes = ["pesde.toml", "LICENSE", "README.md", "src/**"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
Pack = { name = "isoopod/pack", version = "^0.10.1" }
Promise = { wally = "howmanysmall/typed-promise", version = "^4.0.6" }
